config/routes.rb
Rails.application.routes.draw do

  root 'wordgame#game'
  get 'game' => 'wordgame#game'
  get 'score' => 'wordgame#score'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/concerns/boggle_game.rb
class BoggleGame

  class << self
    def generate_grid(grid_size)
      Array.new(grid_size) { ('A'..'Z').to_a[rand(26)] }
    end


    def included?(guess, grid)
      guess.chars.all? { |letter| guess.count(letter) <= grid.count(letter) }
    end

    def compute_score(attempt, time_taken)
      (time_taken > 60.0) ? 0 : attempt.size * (1.0 - time_taken / 60.0)
    end

    def run_game(attempt, grid, start_time, end_time)
      result = { time: end_time - start_time }
      result[:translation] = get_translation(attempt.upcase)
      result[:score], result[:message] = score_and_message(
        attempt, grid, result[:translation], result[:time])
      result
    end

    def score_and_message(attempt,grid, translation, time)
      if included?(attempt.upcase, grid)
        if translation
          score = compute_score(attempt, time)
          [score, "well done"]
        else
          [0, "not an english word"]
        end
      else
        [0, "not in the grid"]
      end
    end


    def get_translation(word)
      api_key = "Your_systran_api_key"
      begin
        response = open("https://api-platform.systran.net/translation/text/translate?source=en&target=fr&key=#{api_key}&input=#{word}")
        json = JSON.parse(response.read.to_s)
        if json['outputs'] && json['outputs'][0] && json['outputs'][0]['output'] && json['outputs'][0]['output'] != word
          return json['outputs'][0]['output']
        end
      rescue
        if File.read('/usr/share/dict/words').upcase.split("\n").include? word.upcase
          return word
        else
          return nil
        end
      end
    end

  end
end

app/controllers/wordgame_controller.rb
class WordgameController < ApplicationController
  def game
    @grid = BoggleGame.generate_grid(9)
    session[:grid] = @grid
    session[:start_time] = Time.now
  end

  def score
    @attempt = params[:word]
    grid = session[:grid]
    start_time = Time.parse(session[:start_time])
    end_time = Time.now
    @result = BoggleGame.run_game(@attempt, grid, start_time, end_time)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/wordgame_helper.rb
module WordgameHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsLongestWordGame</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"%>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/wordgame/game.html.erb
<div class="container">
  <h3 class="text-center">******** Welcome to the longest word-game !********</h3>
  <h4 class="text-center">Here is your grid :</h4>

  <div class="text-center">
    <ul class= "list-inline">
    <% @grid.each do |letter| %>
      <li><%= letter %></li>
    <% end %>
    </ul>
  </div>

  <form action="<%= score_path %>" class="text-center">
    <div class="form-group">
      <label for="letter">Give me your word :   </label>
      <input type="text" class="form-group input-lg" name="word" id="word" placeholder="Jane Doe">

    </div>
    <button type="submit" class="btn btn-primary btn-lg">Submit</button>
  </form>
</div>

app/views/wordgame/score.html.erb
<div class="container">
  <div class="text-center">
    <h1>Résutat</h1>
    <p>Le score obtenu avec le mot <strong>"<%= @attempt %>"</strong> est :</p>
    <p>time : <%= @result[:time]%>, your score : <%= @result[:score] %></p>
  </div>

<div class="text-center"><%= link_to 'Encore un essai ?', root_path %></div>
</div>